// === GENERATED by /slides style — regenerated from palette.json ===
// Do not edit by hand. Edit palette.json and re-run `/slides style desafio-ia-bago-peru-2026`.
import { defineConfig } from 'unocss'

const palette = {
  bg:           '#FFFFFF', // White
  fg:           '#43012A', // Crimson Violet
  primary:      '#AD096B', // Medium Violet Red
  'primary-dk': '#91234A', // Vintage Berry
  accent:       '#FC32AC', // Brilliant Rose
}

export default defineConfig({
  theme: { colors: palette },
  preflights: [{
    getCSS: () => `
      :root {
        --c-bg: ${palette.bg};
        --c-fg: ${palette.fg};
        --c-primary: ${palette.primary};
        --c-primary-dk: ${palette['primary-dk']};
        --c-accent: ${palette['accent']};
      }
      /* !important: deck palette must win over Slidev theme (seriph) defaults */
      .slidev-layout { background: var(--c-bg) !important; color: var(--c-fg) !important; }
      .slidev-layout h1,
      .slidev-layout h2,
      .slidev-layout h3 { color: var(--c-primary) !important; }
      .slidev-layout a { color: var(--c-primary-dk) !important; text-decoration: underline; }
      /* strong: only weight, no auto-color — keeps the page calm.
         For colored emphasis use <strong class="text-accent"> or <span class="text-accent">. */
      .slidev-layout strong { color: inherit; font-weight: 700; }
    `,
  }],
})
